
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "d3c5c5c8-55d7-462c-82ab-9e3a0e313749"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "51c6553e-86fe-42de-afdb-1e283f2fcbe6",
    "account_id_to": "b0bd9858-c833-4895-939f-d60f05e10441",
    "amount": 50
}